### ISSUE TITLE
MinifyBibTexOptionals Discussion

### ISSUE THREAD

**Issue by stefan-kolb** [simonharrer/textools#10]
In my opinion it should not remove any fields from MISC like year etc. as you might not know how MISC is used.
Also, why are you removing volume from ARTICLE?

http://www.ieee.org/documents/ieeecitationref.pdf
http://www.york.ac.uk/integrity/downloads/15663_IEEE%20Style-webFINAL.pdf

**Comment by koppor** [comment]
I also think, that also pages and number should not be removed from article.

**Comment by simonharrer** [comment]
Closing this issue as maintenance is stopped for the tool.
