### ISSUE TITLE
textools will possibly delete bibtex contents if encoding is other than UTF-8

### ISSUE THREAD

**Issue by stefan-kolb** [simonharrer/textools#14]
I had problems when minifying files encoded in JabRef `Cp1252` standard encoding.
This hurts if your not in Git revision :joy:

**Comment by simonharrer** [comment]
I thought it can only open files that are in UTF-8 encoding.

**Comment by simonharrer** [comment]
I thought it can only open files that are in UTF-8 encoding.

**Comment by simonharrer** [comment]
UTF-8 is standard.
